-- Migration: create or align learning_materials table with RLS policies

create table if not exists public.learning_materials (
  id bigint generated by default as identity primary key,
  grade_level text not null,
  subject_name text not null,
  file_name text not null,
  file_url text not null,
  storage_path text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.learning_materials add column if not exists grade_level text;
alter table public.learning_materials add column if not exists subject_name text;
alter table public.learning_materials add column if not exists file_name text;
alter table public.learning_materials add column if not exists file_url text;
alter table public.learning_materials add column if not exists storage_path text;
alter table public.learning_materials add column if not exists created_at timestamptz default timezone('utc', now());
alter table public.learning_materials add column if not exists updated_at timestamptz default timezone('utc', now());

create index if not exists learning_materials_grade_level_idx
  on public.learning_materials (grade_level);

create index if not exists learning_materials_subject_name_idx
  on public.learning_materials (subject_name);

alter table public.learning_materials enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'learning_materials'
      and policyname = 'Public read learning_materials'
  ) then
    create policy "Public read learning_materials"
    on public.learning_materials
    for select
    to public
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'learning_materials'
      and policyname = 'Authenticated insert learning_materials'
  ) then
    create policy "Authenticated insert learning_materials"
    on public.learning_materials
    for insert
    to authenticated
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'learning_materials'
      and policyname = 'Authenticated update learning_materials'
  ) then
    create policy "Authenticated update learning_materials"
    on public.learning_materials
    for update
    to authenticated
    using (true)
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'learning_materials'
      and policyname = 'Authenticated delete learning_materials'
  ) then
    create policy "Authenticated delete learning_materials"
    on public.learning_materials
    for delete
    to authenticated
    using (true);
  end if;
end
$$;
